<?php
session_start();
include 'db.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit;
}

if (!isset($_GET['quiz_id']) || !isset($_GET['questions'])) {
    header("Location: index.php");
    exit;
}

$quiz_id = (int)$_GET['quiz_id'];
$questions_count = (int)$_GET['questions'];

// Get quiz details
$quiz_result = mysqli_query($conn, "SELECT * FROM quizzes WHERE id = $quiz_id AND created_by = {$_SESSION['user_id']}");
$quiz = mysqli_fetch_assoc($quiz_result);

if (!$quiz) {
    header("Location: index.php");
    exit;
}

// Get sample questions for preview
$sample_questions = mysqli_query($conn, "SELECT * FROM questions WHERE quiz_id = $quiz_id LIMIT 3");
?>
<!DOCTYPE html>
<html>
<head>
    <title>AI Quiz Created Successfully - QuizMaster</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Navigation -->
    <div class="navbar">
        <div class="nav-left">
            <h1><a href="index.php" style="color: #333; text-decoration: none;">QuizMaster</a></h1>
        </div>
        <div class="nav-right">
            <span class="greeting-text">Hello, <?php echo htmlspecialchars($_SESSION['username']); ?>!</span>
            <a href="logout.php" class="nav-btn logout-btn">Logout</a>
        </div>
    </div>

    <div class="container">
        <div class="ai-success-container">
            <!-- Success Header -->
            <div class="success-header">
                <div class="success-animation">
                    <div class="success-icon">🎉</div>
                    <div class="ai-badge">🤖 AI Generated</div>
                </div>
                <h2>Quiz Created Successfully!</h2>
                <p>Gemini AI has analyzed your PDF and created an engaging quiz</p>
            </div>

            <!-- Quiz Summary -->
            <div class="quiz-summary-card">
                <div class="summary-header">
                    <h3>📊 Quiz Summary</h3>
                </div>
                
                <div class="summary-details">
                    <div class="detail-row">
                        <span class="detail-label">📚 Quiz Title:</span>
                        <span class="detail-value"><?php echo htmlspecialchars($quiz['title']); ?></span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">❓ Questions Generated:</span>
                        <span class="detail-value highlight"><?php echo $questions_count; ?> Questions</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">🤖 Generated By:</span>
                        <span class="detail-value">Gemini AI</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">📊 Status:</span>
                        <span class="status-badge <?php echo $quiz['status']; ?>">
                            <?php 
                            if ($quiz['status'] === 'pending') {
                                echo '⏳ Pending Admin Approval';
                            } else {
                                echo '✅ Live & Available';
                            }
                            ?>
                        </span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">⏰ Created:</span>
                        <span class="detail-value"><?php echo date('M j, Y g:i A', strtotime($quiz['created_at'])); ?></span>
                    </div>
                </div>
            </div>

            <!-- Sample Questions Preview -->
            <?php if (mysqli_num_rows($sample_questions) > 0): ?>
                <div class="questions-preview-section">
                    <h3>👀 Sample Questions Preview</h3>
                    <p>Here's a preview of some questions AI generated from your PDF:</p>
                    
                    <div class="sample-questions">
                        <?php 
                        $q_num = 1;
                        while ($q = mysqli_fetch_assoc($sample_questions)): 
                        ?>
                            <div class="sample-question">
                                <h4>Question <?php echo $q_num; ?>:</h4>
                                <p class="question-text"><?php echo htmlspecialchars($q['question']); ?></p>
                                
                                <div class="sample-options">
                                    <div class="option <?php echo ($q['correct_option'] === 'A') ? 'correct' : ''; ?>">
                                        <span class="option-letter">A)</span>
                                        <?php echo htmlspecialchars($q['option_a']); ?>
                                        <?php if ($q['correct_option'] === 'A'): ?>
                                            <span class="correct-mark">✓</span>
                                        <?php endif; ?>
                                    </div>
                                    
                                    <div class="option <?php echo ($q['correct_option'] === 'B') ? 'correct' : ''; ?>">
                                        <span class="option-letter">B)</span>
                                        <?php echo htmlspecialchars($q['option_b']); ?>
                                        <?php if ($q['correct_option'] === 'B'): ?>
                                            <span class="correct-mark">✓</span>
                                        <?php endif; ?>
                                    </div>
                                    
                                    <div class="option <?php echo ($q['correct_option'] === 'C') ? 'correct' : ''; ?>">
                                        <span class="option-letter">C)</span>
                                        <?php echo htmlspecialchars($q['option_c']); ?>
                                        <?php if ($q['correct_option'] === 'C'): ?>
                                            <span class="correct-mark">✓</span>
                                        <?php endif; ?>
                                    </div>
                                    
                                    <div class="option <?php echo ($q['correct_option'] === 'D') ? 'correct' : ''; ?>">
                                        <span class="option-letter">D)</span>
                                        <?php echo htmlspecialchars($q['option_d']); ?>
                                        <?php if ($q['correct_option'] === 'D'): ?>
                                            <span class="correct-mark">✓</span>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        <?php 
                        $q_num++;
                        endwhile; 
                        ?>
                    </div>
                </div>
            <?php endif; ?>

            <!-- Action Buttons -->
            <div class="action-buttons-section">
                <?php if ($quiz['status'] === 'approved'): ?>
                    <div class="approved-actions">
                        <h3>🎯 Your quiz is live!</h3>
                        <p>Your AI-generated quiz is now available for everyone to take.</p>
                        <div class="action-buttons">
                            <a href="quiz.php?id=<?php echo $quiz_id; ?>" class="btn-primary">
                                🎮 Take Your Quiz
                            </a>
                            <a href="add_questions.php?quiz_id=<?php echo $quiz_id; ?>" class="btn-secondary">
                                ✏️ Edit Questions
                            </a>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="pending-actions">
                        <h3>⏳ Awaiting Approval</h3>
                        <p>Your AI-generated quiz has been submitted for admin review. Once approved, it will appear on the home page.</p>
                        
                        <div class="approval-timeline">
                            <div class="timeline-step completed">
                                <div class="step-icon">✅</div>
                                <div class="step-content">
                                    <h4>Quiz Generated</h4>
                                    <p>AI successfully created <?php echo $questions_count; ?> questions</p>
                                </div>
                            </div>
                            
                            <div class="timeline-step pending">
                                <div class="step-icon">⏳</div>
                                <div class="step-content">
                                    <h4>Admin Review</h4>
                                    <p>Administrator will review AI-generated content</p>
                                </div>
                            </div>
                            
                            <div class="timeline-step future">
                                <div class="step-icon">🎯</div>
                                <div class="step-content">
                                    <h4>Go Live</h4>
                                    <p>Quiz will be available for everyone to take</p>
                                </div>
                            </div>
                        </div>
                        
                        <div class="action-buttons">
                            <a href="add_questions.php?quiz_id=<?php echo $quiz_id; ?>" class="btn-secondary">
                                ✏️ Review & Edit Questions
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <!-- AI Generation Info -->
            <div class="ai-info-section">
                <h3>🤖 About AI Generation</h3>
                <div class="ai-features">
                    <div class="feature">
                        <span class="feature-icon">🧠</span>
                        <div class="feature-content">
                            <h4>Smart Content Analysis</h4>
                            <p>AI analyzed your PDF content to understand key concepts and topics</p>
                        </div>
                    </div>
                    
                    <div class="feature">
                        <span class="feature-icon">❓</span>
                        <div class="feature-content">
                            <h4>Intelligent Question Creation</h4>
                            <p>Generated questions that test understanding of the material</p>
                        </div>
                    </div>
                    
                    <div class="feature">
                        <span class="feature-icon">🎯</span>
                        <div class="feature-content">
                            <h4>Quality Assurance</h4>
                            <p>Each question includes 4 options with one clearly correct answer</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Navigation Actions -->
            <div class="navigation-actions">
                <a href="ai_quiz_creator.php" class="btn-ai">🤖 Create Another AI Quiz</a>
                <a href="create_quiz.php" class="btn-secondary">✍️ Create Manual Quiz</a>
                <a href="index.php" class="btn-tertiary">🏠 Back to Home</a>
            </div>
        </div>
    </div>
</body>
</html>
